import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Bricolage_Grotesque } from 'next/font/google';
import "./globals.css";
import { chrcy } from "@/lib/fonts";
import { Header } from "@/components/header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bricolage = Bricolage_Grotesque({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-bricolage', 
  // Next.js automatically loads the variable axes for weight and width
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-gray-light font-manrope flex min-h-screen flex-col text-base/5.5 font-normal text-black ${geistSans.variable} ${geistMono.variable} ${chrcy.variable} ${bricolage.variable} antialiased`}
      >
              <Header />
        
        {children}
      </body>
    </html>
  );
}
