import fs from "node:fs/promises";
import path from "node:path";

import { compileMDX } from "next-mdx-remote/rsc";
import remarkGfm from "remark-gfm";
import remarkSlug from "remark-slug";
import rehypeAutolinkHeadings from "rehype-autolink-headings";

import type { TocItem, HealthArticleIndexItem } from "./schema";

import topicsJson from "./topics.json";
const HEALTH_TOPICS = topicsJson as any;

// IMPORTANT: this file is generated by the script
import { HEALTH_LIBRARY_INDEX } from "../_generated/health-library-index";

export type HealthLibraryIndex = {
  topics: Array<{
    slug: string;
    title: string;
    description: string;
    icon?: string;
    order?: number;
    sections?: Array<{ title: string; subtopics: string[] }>;
    counts: { subtopics: number; articles: number };
  }>;
  subtopicsByTopic: Record<
    string,
    Array<{ slug: string; title: string; articleCount: number }>
  >;
  articles: HealthArticleIndexItem[];
};

export function getHealthLibraryIndex(): HealthLibraryIndex {
  return HEALTH_LIBRARY_INDEX as HealthLibraryIndex;
}

export function getTopicConfig(topicSlug: string) {
  return HEALTH_TOPICS.find((t) => t.slug === topicSlug) ?? null;
}

export function getArticlesByTopic(topicSlug: string) {
  const idx = getHealthLibraryIndex();
  return idx.articles.filter((a) => a.frontmatter.topic === topicSlug);
}

export function getArticlesBySubtopic(topicSlug: string, subtopicSlug: string) {
  return getArticlesByTopic(topicSlug).filter(
    (a) => a.frontmatter.subtopic === subtopicSlug,
  );
}

export function getArticleBySlugs(
  topic: string,
  subtopic: string,
  article: string,
) {
  const idx = getHealthLibraryIndex();
  return (
    idx.articles.find(
      (a) =>
        a.frontmatter.topic === topic &&
        a.frontmatter.subtopic === subtopic &&
        a.frontmatter.slug === article,
    ) ?? null
  );
}

export async function loadMdxArticle(filePathFromIndex: string) {
  const absPath = path.isAbsolute(filePathFromIndex)
    ? filePathFromIndex
    : path.join(process.cwd(), filePathFromIndex);

  const source = await fs.readFile(absPath, "utf-8");

  // We already validated frontmatter during index generation.
  // Here, compile MDX and return a renderable React node.
  const compiled = await compileMDX({
    source,
    options: {
      mdxOptions: {
        remarkPlugins: [remarkGfm, remarkSlug],
        rehypePlugins: [
          [
            rehypeAutolinkHeadings,
            {
              behavior: "wrap",
              properties: {
                className: ["anchor-link"],
              },
            },
          ],
        ],
      },
      parseFrontmatter: true,
    },
    components: {
      // Add custom MDX components here later if needed:
      // Callout, Steps, etc.
    },
  });

  return compiled; // { content, frontmatter }
}

// Tiny helper for TOC sidebar
export function flattenToc(toc: TocItem[]) {
  return toc ?? [];
}